version: '3.8'

services:
  plantsmtldb:
    container_name: plantsmtldb
    image: postgres:12.3-alpine
    restart: always
    environment:
        POSTGRES_PASSWORD: postgres
        POSTGRES_USER: postgres
    ports:
      - "5432:5432"
    volumes:
      - dbdataplantsmtl:/var/lib/postgresql/data
    networks:
      - plantsmtl_network

  pgadminplants:
    container_name: plantsmtlpgadmin
    image: dpage/pgadmin4:4.23
    restart: always
    depends_on:
      - plantsmtldb
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "5050:80"
    networks:
      - plantsmtl_network

volumes:
  dbdataplantsmtl:
networks:
  plantsmtl_network:
    driver: bridge